# This .pyi is auto generated by the script in the root folder.
# only for cache,use .py for changes
from toddleocr.config import _, ConfigModel
from toddleocr.datasets.simple import SimpleDataSet
from toddleocr.loss.spin import SPINAttentionLoss
from toddleocr.metrics.rec import RecMetric
from toddleocr.modules.backbones.resnet.rec_resnet_32 import ResNet32
from toddleocr.modules.heads.spin_att import SPINAttentionHead
from toddleocr.modules.necks.rnn import SequenceEncoder
from toddleocr.modules.transforms.gaspin_transformer import GA_SPIN_Transformer
from toddleocr.optim.lr_scheduler import PiecewiseLR
from toddleocr.postprocess.rec import SPINLabelDecode
from toddleocr.transforms.label_ops import SPINLabelEncode
from toddleocr.transforms.operators import DecodeImage, KeepKeys
from toddleocr.transforms.rec_img_aug import SPINRecResizeImg
from torch.optim import AdamW

class Model(ConfigModel):
    use_gpu = True
    epoch_num = 6
    log_window_size = 50
    log_batch_step = 50
    save_model_dir = None
    save_epoch_step = 3
    eval_batch_step = [0, 2000]
    metric_during_train = True
    pretrained_model = None
    checkpoints = None
    save_infer_dir = None
    use_visualdl = False
    character_dict_path = "./ppocr/utils/dict/spin_dict.txt"
    max_text_length = 25
    infer_mode = False
    use_space_char = False
    model_type = "rec"
    algorithm = "SPIN"
    in_channels = 1
    Transform = _(
        GA_SPIN_Transformer, offsets=True, default_type=6, loc_lr=0.1, stn=True
    )
    Backbone = _(ResNet32, out_channels=512)
    Neck = _(
        SequenceEncoder,
        encoder_type="cascadernn",
        hidden_size=256,
        out_channels=[256, 512],
        with_linear=True,
    )
    Head = _(SPINAttentionHead, hidden_size=256)
    loss = SPINAttentionLoss(ignore_index=0)
    metric = RecMetric(main_indicator="acc", is_filter=True)
    postprocessor = SPINLabelDecode(use_space_char=False)
    Optimizer = _(AdamW, beta1=0.9, beta2=0.999)
    LRScheduler = _(
        PiecewiseLR,
        decay_epochs=[3, 4, 5],
        values=[0.001, 0.0003, 9e-05, 2.7e-05],
        clip_norm=5,
    )

    class Data:
        dataset = SimpleDataSet
        root: "train_data/ic15_data" = "train_data/ic15_data/"
        label_file_list: "rec_gt_test.txt" = "rec_gt_train.txt"

    class Loader:
        shuffle: False = True
        drop_last: False = True
        batch_size = 8
        num_workers: 2 = 4
    Transforms = _[
        DecodeImage(img_mode="BGR", channel_first=False),
        SPINLabelEncode() : ...,
        SPINRecResizeImg(
            image_shape=[100, 32], interpolation=2, mean=[127.5], std=[127.5]
        ),
        KeepKeys("image", "label", "length") : ...,
    ]
