# This .pyi is auto generated by the script in the root folder.
# only for cache,use .py for changes
from toddleocr.config import _, ConfigModel
from toddleocr.datasets.lmdb import LMDBDataSet
from toddleocr.loss.ce import CELoss
from toddleocr.metrics.rec import RecMetric
from toddleocr.modules.backbones.resnet.rec_resnet_45 import ResNet45
from toddleocr.modules.heads.abinet import ABINetHead
from toddleocr.optim.lr_scheduler import PiecewiseLR
from toddleocr.postprocess.rec import ABINetLabelDecode
from toddleocr.transforms.label_ops import ABINetLabelEncode
from toddleocr.transforms.operators import DecodeImage, KeepKeys
from toddleocr.transforms.rec_img_aug import ABINetRecAug, ABINetRecResizeImg
from torch.optim import Adam

class Model(ConfigModel):
    use_gpu = True
    epoch_num = 10
    log_window_size = 20
    log_batch_step = 10
    save_model_dir = None
    save_epoch_step = 1
    eval_batch_step = [0, 2000]
    metric_during_train = True
    pretrained_model = None
    checkpoints = None
    save_infer_dir = None
    use_visualdl = False
    character_dict_path = None
    character_type = "en"
    max_text_length = 25
    infer_mode = False
    use_space_char = False
    model_type = "rec"
    algorithm = "ABINet"
    in_channels = 3
    Transform = None
    Backbone = _(
        ResNet45,
    )
    Head = _(ABINetHead, use_lang=True, iter_size=3)
    loss = CELoss(ignore_index=100)
    metric = RecMetric(main_indicator="acc")
    postprocessor = ABINetLabelDecode()
    Optimizer = _(Adam, betas=[0.9, 0.99], clip_norm=20.0)
    LRScheduler = _(PiecewiseLR, decay_epochs=[6], values=[0.0001, 1e-05])

    class Data:
        dataset = LMDBDataSet
        root: "train_data/data_lmdb_release/evaluation/" = (
            "train_data/data_lmdb_release/training/"
        )

    class Loader:
        shuffle: False = True
        drop_last: False = True
        batch_size: 256 = 96
        num_workers = 4
        pin_memory = False
    Transforms = _[
        DecodeImage(img_mode="RGB", channel_first=False),
        ABINetRecAug() :,
        ABINetLabelEncode(ignore_index=100) : ...,
        ABINetRecResizeImg(image_shape=[3, 32, 128]),
        KeepKeys("image", "label", "length") : ...,
    ]
