# This .pyi is auto generated by the script in the root folder.
# only for cache,use .py for changes
from toddleocr.config import _, ConfigModel
from toddleocr.datasets.lmdb import LMDBDataSet
from toddleocr.loss.att import AttentionLoss
from toddleocr.metrics.rec import RecMetric
from toddleocr.modules.backbones.mobilenetv3.rec_mobilenet_v3 import MobileNetV3Rec
from toddleocr.modules.heads.att import AttentionHead
from toddleocr.modules.necks.rnn import SequenceEncoder
from toddleocr.modules.transforms.tps import TPS
from toddleocr.postprocess.rec import AttnLabelDecode
from toddleocr.transforms.label_ops import AttnLabelEncode
from toddleocr.transforms.operators import DecodeImage, KeepKeys
from toddleocr.transforms.rec_img_aug import RecResizeImg
from torch.optim import Adam
from torch.optim.lr_scheduler import ConstantLR

class Model(ConfigModel):
    use_gpu = True
    epoch_num = 72
    log_window_size = 20
    log_batch_step = 10
    save_model_dir = None
    save_epoch_step = 3
    eval_batch_step = [0, 2000]
    metric_during_train = True
    pretrained_model = None
    checkpoints = None
    save_infer_dir = None
    use_visualdl = False
    character_dict_path = None
    max_text_length = 25
    infer_mode = False
    use_space_char = False
    model_type = "rec"
    algorithm = "RARE"
    Transform = _(TPS, num_fiducial=20, loc_lr=0.1, model_name="small")
    Backbone = _(MobileNetV3Rec, scale=0.5, model_name="large")
    Neck = _(SequenceEncoder, encoder_type="rnn", hidden_size=96)
    Head = _(AttentionHead, hidden_size=96)
    loss = AttentionLoss()
    metric = RecMetric(main_indicator="acc")
    postprocessor = AttnLabelDecode()
    Optimizer = _(Adam, betas=[0.9, 0.999], lr=0.0005)
    LRScheduler = _(
        ConstantLR,
    )

    class Data:
        dataset = LMDBDataSet
        root: "train_data/data_lmdb_release/validation/" = (
            "train_data/data_lmdb_release/training/"
        )

    class Loader:
        shuffle: False = True
        drop_last: False = True
        batch_size = 256
        num_workers: 1 = 8
    Transforms = _[
        DecodeImage(img_mode="BGR", channel_first=False),
        AttnLabelEncode() : ...,
        RecResizeImg(image_shape=[3, 32, 100]),
        KeepKeys("image", "label", "length") : ...,
    ]
