from .det_resnet import ResNet
from .det_resnet_vd import ResNet_vd
from .det_resnet_vd_sast import ResNet_SAST
from .e2e_resnet_vd_pg import ResNet_E2E
from .rec_resnet_31 import ResNet31
from .rec_resnet_32 import ResNet32
from .rec_resnet_45 import ResNet45
from .rec_resnet_aster import ResNet_ASTER
from .rec_resnet_fpn import ResNetFPN
from .rec_resnet_rfl import ResNetRFL
from .rec_resnet_vd import ResNet_Rec_Vd
