# This .pyi is auto generated by the script in the root folder.
# only for cache,use .py for changes
from toddleocr.config import _, ConfigModel
from toddleocr.datasets.simple import SimpleDataSet
from toddleocr.loss.sast import SASTLoss
from toddleocr.metrics.det import DetMetric
from toddleocr.modules.backbones.resnet.det_resnet_vd_sast import ResNet_SAST
from toddleocr.modules.heads.sast import SASTHead
from toddleocr.modules.necks.sast_fpn import SASTFPN
from toddleocr.postprocess.sast import SASTPostProcess
from toddleocr.transforms.label_ops import DetLabelEncode
from toddleocr.transforms.operators import (
    DecodeImage,
    DetResizeForTest,
    KeepKeys,
    NormalizeImage,
    ToCHWImage,
)
from toddleocr.transforms.sast_process import SASTProcessTrain
from torch.optim import Adam
from torch.optim.lr_scheduler import ConstantLR

class Model(ConfigModel):
    use_gpu = True
    epoch_num = 5000
    log_window_size = 20
    log_batch_step = 2
    save_model_dir = None
    save_epoch_step = 1000
    eval_batch_step = [4000, 5000]
    metric_during_train = False
    pretrained_model = None
    checkpoints = None
    save_infer_dir = None
    use_visualdl = False
    model_type = "det"
    algorithm = "SAST"
    Transform = None
    Backbone = _(ResNet_SAST, layers=50)
    Neck = _(SASTFPN, with_cab=True)
    Head = _(
        SASTHead,
    )
    loss = SASTLoss()
    metric = DetMetric(main_indicator="hmean")
    postprocessor = SASTPostProcess(
        score_thresh=0.5,
        sample_pts_num=6,
        nms_thresh=0.2,
        expand_scale=1.2,
        shrink_ratio_of_width=0.2,
    )
    Optimizer = _(Adam, betas=[0.9, 0.999], lr=0.001)
    LRScheduler = _(
        ConstantLR,
    )

    class Data:
        dataset = SimpleDataSet
        root = "train_data/"
        label_file_list: "total_text_icdar_14pt/test_label_json.txt" = [
            "art_latin_icdar_14pt/train_no_tt_test/train_label_json.txt",
            "total_text_icdar_14pt/train_label_json.txt",
        ]

    class Loader:
        shuffle: False = True
        drop_last = False
        batch_size: 1 = 4
        num_workers: 2 = 4
    Transforms = _[
        DecodeImage(img_mode="BGR", channel_first=False),
        DetLabelEncode() : ...,
        SASTProcessTrain(
            image_shape=[512, 512],
            min_crop_side_ratio=0.3,
            min_crop_size=24,
            min_text_size=4,
            max_text_size=512,
        ) :,
        : DetResizeForTest(resize_long=768),
        : NormalizeImage(
            scale="1./255.",
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225],
            order="hwc",
        ),
        : ToCHWImage(),
        KeepKeys(
            "image", "score_map", "border_map", "training_mask", "tvo_map", "tco_map"
        ) : KeepKeys("image", "shape", "polys", "ignore_tags") : ...,
    ]
