# This .pyi is auto generated by the script in the root folder.
# only for cache,use .py for changes
from ptocr.config import ConfigModel,_
from ptocr.modules.backbones.resnet.det_resnet_vd import ResNet_vd
from ptocr.modules.necks.fce_fpn import FCEFPN
from ptocr.modules.heads.fce import FCEHead
from ptocr.loss.fce import FCELoss
from ptocr.metrics.det import DetFCEMetric
from ptocr.postprocess.fce import FCEPostProcess
from torch.optim import Adam
from torch.optim.lr_scheduler import ConstantLR
from ptocr.datasets.simple import SimpleDataSet
from ptocr.transforms.operators import DecodeImage, NormalizeImage, KeepKeys, DetResizeForTest, Pad, ToCHWImage
from ptocr.transforms.label_ops import DetLabelEncode
from ptocr.transforms.ColorJitter import ColorJitter
from ptocr.transforms.fce_aug import RandomRotatePolyInstances, SquareResizePad, RandomCropFlip, RandomCropPolyInstances, RandomScaling
from ptocr.transforms.iaa_augment import IaaAugment
from ptocr.transforms.fce_targets import FCENetTargets
class Model(ConfigModel):
    use_gpu = True
    epoch_num = 1500
    log_window_size = 20
    log_batch_step = 20
    save_model_dir = None
    save_epoch_step = 100
    eval_batch_step = [0, 835]
    metric_during_train = False
    pretrained_model = None
    checkpoints = None
    save_infer_dir = None
    use_visualdl = False
    model_type = 'det'
    algorithm = 'FCE'
    Transform = None
    Backbone = _(ResNet_vd, layers=50, dcn_stage=[False, True, True, True], out_indices=[1, 2, 3])
    Neck = _(FCEFPN, out_channels=256, has_extra_convs=False, extra_stage=0)
    Head = _(FCEHead, fourier_degree=5)
    loss = FCELoss(fourier_degree=5, num_sample=50)
    metric = DetFCEMetric(main_indicator="hmean")
    postprocessor = FCEPostProcess(scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, box_type="poly")
    Optimizer = _(Adam,betas=[0.9, 0.999], lr=0.0001)
    LRScheduler = _(ConstantLR,)
    class Data:
        dataset = SimpleDataSet
        root = "train_data/ctw1500/imgs/"
        label_file_list:"test.txt" = "training.txt"
    class Loader:
        shuffle:False = True
        drop_last = False
        batch_size:1 = 6
        num_workers:2 = 8
    Transforms = _[DecodeImage(img_mode="BGR", channel_first=False, ignore_orientation=True),DetLabelEncode():...,ColorJitter(brightness=0.142, saturation=0.5, contrast=0.5):,RandomScaling():,RandomCropFlip(crop_ratio=0.5):,RandomCropPolyInstances(crop_ratio=0.8, min_side_ratio=0.3):,RandomRotatePolyInstances(rotate_ratio=0.5, max_angle=30, pad_with_fixed_color=False):,SquareResizePad(target_size=800, pad_ratio=0.6):,IaaAugment(augmenter_args=[{'type': 'Fliplr', 'args': {'p': 0.5}}]):,FCENetTargets(fourier_degree=5):,:DetResizeForTest(limit_type="min", limit_side_len=736),NormalizeImage(scale="1./255.", mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], order="hwc"),:Pad(),ToCHWImage(),KeepKeys("image","p3_maps","p4_maps","p5_maps"):KeepKeys("image","shape","polys","ignore_tags"):...]